### PR TITLE
[WIP] Updates on Components properties 

### PR DESCRIPTION
**Pull request by williamdaconceicao**
Single components properties file created

### CODE REVIEW

**Comment by williamdaconceicao** [comment]
` Object.keys(test[key]).forEach((value) => {
 +        console.log(value);
 +        test[key].aa.forEach(e => console.log(e));
 +      });
`
On the 'test.js' line 24, (code is at the top), I want to replace the "aa" with the variable "value" wich is created with an forEach is it possible ?

**Comment by williamdaconceicao** [comment]
```
<Grid>
      <Inner>
        {Head.map(title => <Cell key={title}>{title}</Cell>)}
      </Inner>
      {Object.keys(PropertyJson).forEach(props => {
        if (props === Component.name) {
          if (PropertyJson[props].length === undefined) {
            Object.keys(PropertyJson[props]).forEach((GeneralPropertyName) => {
              PropertyJson[props][GeneralPropertyName].forEach(element =>
                (
                  <Inner style={{ paddingBottom: "16px" }}>
                    {element.forEach(value => <Cell> {value} </Cell>)}
                  </Inner>
                ));
            });
          } else {
            PropertyJson[props].forEach(element =>
              (
                <Inner style={{ paddingBottom: "16px" }}>
                  {element.map(value => <Cell key={value}>{value}</Cell>)}
                </Inner>
              ));
          }
        }
      })}
      <div>Salut</div>
    </Grid>
```
Here's an very strange bug: elements create into my second part ( after the first <Inner> ) don't render. I don't see something but what?

**Comment by williamdaconceicao** [comment]
```
  return (
    <Grid>
      <Inner>
        {Head.map(title => <Cell key={title}>{title}</Cell>)}
      </Inner>
      {Object.keys(PropertyJson).map(props => {
        if (props === Component.name) {
          if (PropertyJson[props].length === undefined) {
            Object.keys(PropertyJson[props]).map((GeneralPropertyName) => {
              PropertyJson[props][GeneralPropertyName].map(element =>
                (
                  <Inner style={{ paddingBottom: "16px" }}>
                    {element.map(value => <Cell key={value}> {value} </Cell>)}
                  </Inner>
                ));
            });
          } else {
            PropertyJson[props].map(element =>
              (
                console.log("salut"),
                <Inner style={{ paddingBottom: "16px" }}>
                  {element.map(value => <Cell key={value}>{value}</Cell>)}
                </Inner>
              ));
          }
        }
      })}
    </Grid>
  )
```
Here's an interresting bug: The elements create inside the "Object.keys(PropertyJson).map" don't render. I guess I forgot something but what ?

**Comment by williamdaconceicao** [comment]
```
(bodySingle.map(e => (
            <Inner>
              {e.map(value =><Cell key={value.id}>{value}</Cell>)}
            </Inner>,
            <div style={{ borderBottom: "solid black 1px" }} />
          )))
```
In this code, the Inner component don't render ( only the div is rendered ) 

bodySingle look like an array of array of string.

**Comment by willdurand** [comment]
@williamdaconceicao I'd like to see a better diff, could you please rebase your PR? (no squash yet)

**Comment by willdurand** [comment]
I dont understand this line either:

```
<Cell style={{ fontSize: "20px", fontWeight: "bold" }}>{(count += 1), PropsValue[count]}</Cell>
```

Whats the intent? Using ` {}` in JSX means you add JavaScript code. I dont really know what JavaScript code separated by a comma does.

**Pull request closed without merging**
