### PR TITLE
Add every properties of the components

### PR DESCRIPTION
**Pull request by williamdaconceicao**
Every  properties as been added.

### CODE REVIEW

**Comment by mikbry** [comment]
code is not ok, didn"t pass lint

**Comment by willdurand** [comment]
@mikbry he could update his PR layer, so I would keep it open so that we can do code review and so on until it gets better and we can merge it.

**Comment by willdurand** [comment]
@williamdaconceicao looks like you need to configure your editor to use unix end of line + git https://help.github.com/articles/dealing-with-line-endings/#platform-windows

**Comment by williamdaconceicao** [comment]
Yes, I know I did some wrong manipulation with my IDE and git :) I'm about to change it ;)

**Comment by willdurand** [comment]
Good! Now you should squash your commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html and rebase your branch on top of `master`.

**Pull request merged**
